# Site Info
title:              "ege'nin web günlüğü"
description:        "Sanırım buraya bir şeyler yazacağım."
author_name:        "Ege"
logo_url:           https://avatars0.githubusercontent.com/u/30394812?v=4

# Site Settings
url:                https://egecue.github.io # main url
baseurl:            /blog
permalink:          /:title # Post permalink
timezone:           Europe/Istanbul # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
plugins:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
